name: Continuous Integration

on: [push]

jobs:
  build:
    name: Build and publish package
    runs-on: ubuntu-24.04

    permissions:
      packages: write

    env:
      BUILD_CONFIG: Release
      SOLUTION: NHSUKFrontendRazor.sln
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      NUGET_PACKAGE: DotnetViewComponents

    strategy:
      matrix:
        dotnet-version: ['3.1.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ICU library
        run: sudo apt-get update && sudo apt-get install -y libicu-dev

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.2
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.2

      - name: Display GitVersion outputs
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersion }}"

      - name: Package nuget
        run: dotnet pack "$SOLUTION" --configuration "$BUILD_CONFIG" -o package /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }}
